### ISSUE TITLE
brew install concorde no longer works

### ISSUE THREAD

**Issue by Carpetfizz** [jvkersch/pytsp#6]
```
mac:Downloads me$ brew install concorde
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
exim                                     grib-api

Error: No available formula with the name "concorde" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
ajays-mbp:Downloads ajay$ brew info concorde
Error: No available formula with the name "concorde" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
```

**Comment by jvkersch** [comment]
Ah, that's a bummer. I'm thinking of packaging Concorde with pytsp (and releasing a wheel on PyPI), but in the meantime, are you OK with building Concorde from scratch yourself?

**Comment by Carpetfizz** [comment]
That's cool. And yeah, I was able to build Concorde from scratch using your instructions.

**Comment by jvkersch** [comment]
@Carpetfizz Thanks for bringing this up. This (and many other useful recipes) used to be in the now-deprecated homebrew/science repo, and it's a pity that this is not around anymore. In the meantime, I've updated the `tools/build_concorde.sh` script in the repository so that it works on mac OS as well. I've updated the README to reflect the new usage instructions.

**Comment by Carpetfizz** [comment]
Thanks for being proactive about fixing this issue. You definitely helped my friends and I complete our class project in time!
