### ISSUE TITLE
No module named pytsp.tsp 

### ISSUE THREAD

**Issue by Carpetfizz** [jvkersch/pytsp#7]
```
>>> from pytsp.tsp import TSPSolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pytsp.tsp'
```

**Comment by jvkersch** [comment]
@Carpetfizz This is probably because of the install failures with Brew you reported in #6

**Comment by mertbulan** [comment]
@jvkersch I am getting same error after installed via #8

**Comment by jvkersch** [comment]
@mertbulan Can you let me know how you installed the package?

**Comment by mertbulan** [comment]
@jvkersch after your last commit, it works now. Thank you!
